language: node_js
node_js:
  - "6"
sudo: false
cache:
  directories:
    - $HOME/.nvm
    - $HOME/.npm
    - node_modules
before_install:
  - npm install npm@latest -g
  - npm config set spin false
after_success: npm run coverage
